export const FETCH_LOGIN_START = 'FETCH_DATA_START';
export const FETCH_LOGIN_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_LOGIN_ERROR = 'FETCH_DATA_ERROR';

export const FETCH_REGISTER_START = 'FETCH_REGISTER_START';
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_ERROR = 'FETCH_REGISTER_ERROR';

export const OPEN_MODAL_NEWPOST = 'OPEN_MODAL_NEWPOST';
export const CLOSE_MODAL_NEWPOST = 'CLOSE_MODAL_NEWPOST';

export const DELETE_POST_START = 'DELETE_POST_START';
export const DELETE_POST_SUCCESS = 'DELETE_POST_SUCCESS';
export const DELETE_POST_ERROR = 'DELETE_POST_ERROR';

export const CLOSE_SNACK_BAR = 'CLOSE_SNACK_BAR';
export const USE_SNACK_BAR = 'USE_SNACK_BAR';

export const UPDATE_POST_START = 'UPDATE_POST_START';
export const UPDATE_POST_SUCCESS = 'UPDATE_POST_SUCCESS';
export const UPDATE_POST_ERROR = 'UPDATE_POST_ERROR';

export const CLEAR_CATEGORIES = 'CLEAR_CATEGORIES';

export const CHANGE_POST = 'CHANGE_POST';

export const GET_POSTS_START = 'GET_POSTS_START';
export const GET_POSTS_SUCCESS = 'GET_POSTS_SUCCESS';
export const GET_POSTS_ERROR = 'GET_POSTS_ERROR';

export const GET_POST_START = 'GET_POST_START';
export const GET_POST_SUCCESS = 'GET_POST_SUCCESS';
export const GET_POST_ERROR = 'GET_POST_ERROR';

export const GET_POST_UPDATE_START = 'GET_POST_UPDATE_START';
export const GET_POST_UPDATE_SUCCESS = 'GET_POST_UPDATE_SUCCESS';
export const GET_POST_UPDATE_ERROR = ' GET_POST_UPDATE_ERROR';

export const DELETE_COMMENT_SUCCESS = 'DELETE_COMMENT_SUCCESS';
export const DELETE_COMMENT_ERROR = 'DELETE_COMMENT_ERROR';
export const DELETE_COMMENT_START = 'DELETE_COMMENT_START';

export const DELETE_CATEGORY_START = 'DELETE_CATEGORY_START';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_ERROR = 'DELETE_CATEGORY_ERROR';

export const CHANGE_POST_CATEGORY_START = 'CHANGE_POST_CATEGORY_START';
export const CHANGE_POST_CATEGORY_SUCCESS = 'CHANGE_POST_CATEGORY_SUCCESS';
export const CHANGE_POST_CATEGORY_ERROR = 'CHANGE_POST_CATEGORY_ERROR';

export const CLEAR_INPUTS_NEWPOST = 'CLEAR_INPUTS_NEWPOST';

export const GET_COMMENTS_START = 'GET_COMMENTS_START';
export const GET_COMMENTS_SUCCESS = 'GET_COMMENTS_SUCCESS';
export const GET_COMMENTS_ERROR = 'GET_COMMENTS_ERROR';

export const GET_CATEGORY_START = 'GET_CATEGORY_START';
export const GET_CATEGORY_SUCCESS = 'GET_CATEGORY_SUCCESS';
export const GET_CATEGORY_ERROR = 'GET_CATEGORY_ERROR';

export const SEND_COMMENT_START = 'SEND_COMMENT_START';
export const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS';
export const SEND_COMMENT_ERROR = 'SEND_COMMENT_ERROR';

export const GET_USER_START = 'GET_USER_START';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';

export const DISPATCH_USER_ID = 'DISPATCH_USER_ID';

export const GET_USER_BY_ID_START = 'GET_USER_BY_ID_START';
export const GET_USER_BY_ID_SUCCESS = 'GET_USER_BY_ID_SUCCESS';
export const GET_USER_BY_ID_ERROR = 'GET_USER_BY_ID_ERROR';

export const SENDING_NEWPOST_START = 'SENDING_NEWPOST_START';
export const SENDING_NEWPOST_SUCCESS = 'SENDING_NEWPOST_SUCCESS';
export const SENDING_NEWPOST_ERROR = 'SENDING_NEWPOST_ERROR';

export const REGISTER_INPUTS_VALID = 'REGISTER_INPUTS_VALID';
export const LOGIN_INPUTS_VALID = 'LOGIN_INPUTS_VALID';
export const NEWPOST_INPUTS_VALID = 'NEWPOST_INPUTS_VALID';

export const REGISTER_INPUTS_CHANGE = 'REGISTER_INPUTS_CHANGE';
export const LOGIN_INPUTS_CHANGE = 'LOGIN_INPUTS_CHANGE';
export const NEWPOST_INPUTS_CHANGE = 'NEWPOST_INPUTS_CHANGE';

export const LOGOUT_ACCOUNT_SUCCESS = 'LOGOUT_ACCOUNT_SUCCESS';
export const LOGOUT_ACCOUNT_ERROR = 'LOGOUT_ACCOUNT_ERROR';
