export const FETCH_LOGIN_START = 'FETCH_DATA_START';
export const FETCH_LOGIN_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_LOGIN_ERROR = 'FETCH_DATA_ERROR';

export const FETCH_REGISTER_START = 'FETCH_REGISTER_START';
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_ERROR = 'FETCH_REGISTER_ERROR';