export const FETCH_LOGIN_START = 'FETCH_DATA_START';
export const FETCH_LOGIN_SUCCESS = 'FETCH_DATA_SUCCESS';
export const FETCH_LOGIN_ERROR = 'FETCH_DATA_ERROR';

export const FETCH_REGISTER_START = 'FETCH_REGISTER_START';
export const FETCH_REGISTER_SUCCESS = 'FETCH_REGISTER_SUCCESS';
export const FETCH_REGISTER_ERROR = 'FETCH_REGISTER_ERROR';


export const FETCH_AUTH_START = 'FETCH_AUTH_START';
export const FETCH_AUTH_SUCCESS = 'FETCH_AUTH_SUCCESS';
export const FETCH_AUTH_ERROR = 'FETCH_AUTH_ERROR';

export const REGISTER_INPUT_VALID = 'REGISTER_INPUT_VALID'
export const LOGIN_INPUT_VALID = 'LOGIN_INPUT_VALID'

export const LOGOUT_ACCOUNT_SUCCESS = 'LOGOUT_ACCOUNT_SUCCESS'
export const LOGOUT_ACCOUNT_ERROR = 'LOGOUT_ACCOUNT_ERROR'